export const VALIDATOR_CHECK = "VALIDATOR_CHECK";
export const TOKEN_SET = "TOKEN_SET";
export const TOKEN_EXPIRY_TIME = "TOKEN_EXPIRY_TIME";

export const SEARCH_QUERY = "SEARCH_QUERY";
export const SEARCH_QUERY_REMOVE = "SEARCH_QUERY_REMOVE";

export const GET_SELLERS = "GET_SELLERS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORIES_LOADER = "CATEGORIES_LOADER";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ALL_PRODUCTS_LOADER = "ALL_PRODUCTS_LOADER";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const INCREMENT_ITEM_QUANTITY = "INCREMENT_ITEM_QUANTITY";
export const DECREMENT_ITEM_QUANTITY = "DECREMENT_ITEM_QUANTITY";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const DELETE_TOTAL_CART = "DELETE_TOTAL_CART";

export const DELIVERY_ADDRESS_ADD = "DELIVERY_ADDRESS_ADD";
export const DELIVERY_ADDRESS_REMOVE = "DELIVERY_ADDRESS_REMOVE";
